server:
  port: 8082

Spring:
  profiles:
    active: dev

---

spring:
  profile: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: ashutosh@rootuser159
    url: jdbc:mysql://localhost:3306/DeptDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to SpringBoot Demo

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "beans, env"

---

spring:
  profile: qa
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: ashutosh@rootuser159
    url: jdbc:mysql://localhost:3306/DeptDB_qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to SpringBoot Demo

---

spring:
  profile: prod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: ashutosh@rootuser159
    url: jdbc:mysql://localhost:3306/DeptDB_prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to SpringBoot Demo


